package org.flatizy.flatizy.entity.enums;

public enum UserSessionState {
    IDLE,
    WAITING_FOR_INVITE_LINK,
    CREATING_INVITE_LINK_SELECTING_APARTMENTS,
    CREATING_INVITE_LINK_USES,
    CREATING_INVITE_LINK_DAYS,

    CREATING_FEEDBACK,

    CREATING_REQUEST_SELECTING_TYPE,
    CREATING_REQUEST_SELECTING_APARTMENT,
    CREATING_REQUEST_ENTERING_DESCRIPTION
}
