spring.application.name=Flatizy
server.port=8083


telegram.bot.token=8344691326:AAHeXhlqlXKjNWs0SBxfOv01QCpoaHvwrsg
telegram.bot.username=FlatizyBot
telegram.bot.webhook-path=/telegram/webhook

telegram.webhook.secret-token=dcc167cb16d549dcf886df63083b7474418f3fc3cbaf3e29f666811263ca9f98
telegram.webhook.url=https://whitley-neourthodox-eliana.ngrok-free.dev/telegram/webhook

apartments.external.api.url=http://localhost:8083/api/apartments/fetch-external-mock
billing.api.url=http://localhost:8083/api/accounts/mock
billing.debt.api.url=http://localhost:8083/api/accounts/debts-mock


# ===================== POSTGRESQL ============================
spring.datasource.url=jdbc:postgresql://localhost:5432/Flatizy
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================== JPA / Hibernate =========================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
