spring.application.name=Flatizy
telegram.api.id=21158463
telegram.api.hash=c9aef9381e040fc9773024db7f2483b5
telegram.bot.token=8344691326:AAFEamcvNZ0Hejm0UdoASb9jQpY6kBd8wnI
python.path=python
python.script.contacts.path=scripts/telegram_contacts.py
python.script.auth.path=scripts/telegram_auth.py
telegram.contacts.path=src/main/resources/contacts.json

