spring.application.name=Flatizy
server.port=8083

telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.bot.username=FlatizyBot
telegram.bot.webhook-path=/telegram/webhook

telegram.webhook.secret-token=${TELEGRAM_WEBHOOK_SECRET}
telegram.webhook.url=https://whitley-neourthodox-eliana.ngrok-free.dev/telegram/webhook

apartments.external.api.url=http://localhost:8083/api/apartments/fetch-external-mock
billing.api.url=http://localhost:8083/api/accounts/mock
billing.debt.api.url=http://localhost:8083/api/accounts/debts-mock

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true